server:
  port: 8888
spring:
  cloud:
    gateway:
      routes:
        - id: finance-route
          uri: lb://finance-all
          predicates:
            - Path=/finance/**
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: finance-gateway